# renovate: datasource=github-tags depName=romkatv/powerlevel10k
p10k_version: "v1.19.0"
# renovate: datasource=github-tags depName=pyenv/pyenv
pyenv_version: "v2.3.35"
# renovate: datasource=github-tags depName=nodejs/node
nodejs_version: "v21.7.3"
# renovate: datasource=github-tags depName=unxsh/nitch versioning=docker
nitch_version: "0.1.6"
# renovate: datasource=golang-version depName=go
go_version: "1.21.6"
