# renovate: datasource=github-tags depName=romkatv/powerlevel10k
p10k_version: "v1.16.1"
# renovate: datasource=github-tags depName=pyenv/pyenv
pyenv_version: "v2.3.9"
# renovate: datasource=github-tags depName=nodejs/node
nodejs_version: "v18.12.0"
# renovate: datasource=github-tags depName=unxsh/nitch versioning=pep440
nitch_version: "0.1.6"
