# renovate: datasource=github-tags depName=romkatv/powerlevel10k
p10k_version: "v1.15.0"
# renovate: datasource=github-releases depName=pyenv/pyenv
pyenv_version: "v2.3.8"
# renovate: datasource=github-tags depName=nodejs/node versioning=node
nodejs_version: "v18.11.0"
# renovate: datasource=github-tags depName=epk/SF-Mono-Nerd-Font
sfmono_version: "v15"
