# renovate: datasource=github-tags depName=romkatv/powerlevel10k
p10k_version: "v1.16.1"
# renovate: datasource=github-tags depName=pyenv/pyenv
pyenv_version: "v2.3.9"
# renovate: datasource=github-tags depName=nodejs/node versioning=node
nodejs_version: "18.12.1"
